#!/bin/bash

# A bash script that helps me create notes in my second brain
# based on my "blog" script
# TODO
# 1. check if file already exists
# 2. write this in Go :)

# function to prompt the user for a filename
get_filename() {
	read -p "Enter a subject: " filename
	echo "$filename"
}

# function to create and open a file in the specified directory
open_file() {

	# Cd into the directory
	cd "$1" || exit

if [ ! -f "$filename.md" ]; then
	nvim '+ normal ggzzi' "$filename.md" -c ":ObsidianTemplate inb-core" -c ":NoNeckPain" -c "normal! gg$" -c "startinsert"
else	
	nvim '+ normal ggzzi' "$filename.md" -c ":NoNeckPain" -c "normal! gg$" -c "startinsert"
fi
}

# Prompt the user if no filename is provided
if [[ $# -eq 0 ]]; then
	filename=$(get_filename)
fi

# if more than one argument is given, print error message and stop script
if [[ $# -gt 1 ]]; then
	echo "Please provide only one filename separated by dashes, without .md extension."
	echo "Example: zet my-new-note"
	exit 1
fi

# set filename to the argument given to the script
if [[ $# -eq 1 ]]; then
	filename=$1
fi

open_file "$MIND_PALACE/0-inbox/"
