#!/bin/bash

# creates a new script in my scripts collection

# check if script name is provided

name=$1

if [ $# -eq 0 ]; then
	# ask for name of script
	echo "Please provide a name for the script"
	read -r name
fi

if [ -f "$SCRIPTS/$name" ]; then
    echo "Script already exists. Opening for editing..."
    nvim "$SCRIPTS/$name"
else
    # Create a new script
    cd "$SCRIPTS" || exit
    touch "$name"
    chmod +x "$name"
		(cd $ENV_HOME && stow -R .)
    echo "#!/bin/bash" >"$name"
    nvim "$SCRIPTS/$name"
fi
